### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by cvanderlei** [Patent2net/P2N#10]
Processing the Drone case, it shows the following error message:

Traceback (most recent call last):
  File "<string>", line 210, in <module>
  File "<string>", line 133, in complete3
  File "<string>", line 110, in LectureFichier2
UnboundLocalError: local variable 'lect' referenced before assignment

[drone.cql.txt](https://github.com/Patent2net/P2N/files/692114/drone.cql.txt)

**Comment by Quoniam** [comment]
When processing from crash... error did not appears...
