### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#11]
with the cashew case...
include the full case cql, errors_logs, gathered, printscreen

[cashew.zip](https://github.com/Patent2net/P2N/files/698609/cashew.zip)
[Cashew_ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/698607/Cashew_ErrorsLogs.zip)
[Errors Cashew.txt](https://github.com/Patent2net/P2N/files/698608/Errors.Cashew.txt)
[cashew.cql.txt](https://github.com/Patent2net/P2N/files/698613/cashew.cql.txt)

Traceback (most recent call last):
  File "<string>", line 330, in <module>
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsV2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 2122, in LoadBiblioFile
IOError: [Errno 2] No such file or directory: '..//DATA//cashew//PatentBiblios//Descriptioncashew'
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: Traceback (most recent call last):
Traceback (most recent call last):
n  File "<string>", line 167, in <module>
  File "<string>", line 167, in <module>
ame 'DataBrevet' is not definedNameErrorNameError:
: nname 'DataBrevet' is not definedame 'DataBrevet' is not defined

Traceback (most recent call last):
  File "<string>", line 167, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameErrorNameError  File "<string>", line 167, in <module>
: : NameErrornn: ame 'DataBrevet' is not definedame 'DataBrevet' is not definedn

ame 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 62, in <module>
Traceback (most recent call last):
KeyError  File "<string>", line 66, in <module>
: KeyError': brevets''
brevets'
Traceback (most recent call last):
  File "<string>", line 62, in <module>
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "<string>", line 69, in <module>
KeyError: 'brevets'
Traceback (most recent call last):
  File "<string>", line 68, in <module>
KeyError: 'brevets'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 2, in read_gpickle
  File "<string>", line 122, in <module>
  File "<string>", line 122, in <module>
  File "<string>", line 122, in <module>
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
  File "<string>", line 2, in read_gpickle
IOError  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
: IOErrorIOError  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
[: : IOErrorErrno 2] No such file or directory: '../DATA/cashew/tempo/_InventorsCrossTech'[[:
Errno 2] No such file or directory: '../DATA/cashew/tempo/_CrossTech'Errno 2] No such file or directory: '../DATA/cashew/tempo/_CountryCrossTech'[

Errno 2] No such file or directory: '../DATA/cashew/tempo/_Applicants_CrossTech'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOErrorIOError: : [[Errno 2] No such file or directory: '../DATA/cashew/tempo/_CountryCrossTech'Errno 2] No such file or directory: '../DATA/cashew/tempo/_Applicants_CrossTech'

Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOErrorTraceback (most recent call last):
:   File "<string>", line 126, in <module>
[  File "<string>", line 2, in read_gpickle
Errno 2] No such file or directory: '../DATA/cashew/tempo/_CrossTech'  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file

IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_InventorsCrossTech'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Inventors'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_ApplicantInventor'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Applicants'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_References'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Inventors'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 126, in <module>
Traceback (most recent call last):
  File "<string>", line 2, in read_gpickle
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
: IOError: IOError[Errno 2] No such file or directory: '../DATA/cashew/tempo/_Applicants':
[[Errno 2] No such file or directory: '../DATA/cashew/tempo/_References'Errno 2] No such file or directory: '../DATA/cashew/tempo/_ApplicantInventor'

Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Citations'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Equivalents'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Citations'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/cashew/tempo/_Equivalents'
Traceback (most recent call last):
  File "<string>", line 68, in <module>
Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "C:\_lab\P2N\Patent2Net\build\FormateExportPivotTable\out00-PYZ.pyz\P2N_Lib", line 2122, in LoadBiblioFile
IOError: [IOErrorErrno 2] No such file or directory: '..//DATA//cashew//PatentBiblios//Familiescashew':
[Errno 2] No such file or directory: '..//DATA//cashew//PatentBiblios//Descriptioncashew'
Traceback (most recent call last):
  File "<string>", line 210, in <module>
NameError: name 'LstBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 204, in <module>
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: '..//DATA//cashew//PatentContents//Claims/*.*'
Traceback (most recent call last):
  File "<string>", line 62, in <module>
NameError: name 'data' is not defined
cashew.cql  processed

**Comment by Quoniam** [comment]
solved
