### ISSUE TITLE
New case Issue

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#13]
Hi,
When running the 3D print case ... lot of errors too...

[3D print errors.txt](https://github.com/Patent2net/P2N/files/701794/3D.print.errors.txt)
[3D print_ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/701793/3D.print_ErrorsLogs.zip)
[3Dprint.cql.txt](https://github.com/Patent2net/P2N/files/701796/3Dprint.cql.txt)
[3Dprint.zip](https://github.com/Patent2net/P2N/files/701795/3Dprint.zip)

C:\Users\Public\Softs\Luc P2N-V2>ECHO OFF
Processing... plese wait...
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
done saving requete, replaced by ..\REQUESTS\3Dprint.cql
C:\Users\Public\Softs\LUCP2N~1\PATENT~1\dateutil\parser.py:330: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 330, in <module>
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsV2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 2122, in LoadBiblioFile
IOError: [Errno 2] No such file or directory: '..//DATA//3Dprint//PatentBiblios//Description3Dprint'
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 167, in <module>
  File "<string>", line 167, in <module>
  File "<string>", line 167, in <module>
NameErrorNameError: : nnNameErrorame 'DataBrevet' is not defined:
name 'DataBrevet' is not defined
ame 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 167, in <module>
NameError: name 'DataBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 62, in <module>
Traceback (most recent call last):
KeyError  File "<string>", line 66, in <module>
: KeyError': brevets''
brevets'
Traceback (most recent call last):
  File "<string>", line 69, in <module>
KeyError: 'brevets'
Traceback (most recent call last):
  File "<string>", line 62, in <module>
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "<string>", line 68, in <module>
KeyError: 'brevets'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 2, in read_gpickle
  File "<string>", line 122, in <module>
  File "<string>", line 122, in <module>
  File "<string>", line 122, in <module>
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOErrorIOError:   File "<string>", line 2, in read_gpickle
:   File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
[  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
[Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_CountryCrossTech'
IOErrorIOErrorErrno 2] No such file or directory: '../DATA/3Dprint/tempo/_Applicants_CrossTech':
: [[Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_InventorsCrossTech'Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_CrossTech'

Traceback (most recent call last):
  File "<string>", line 126, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 2, in read_gpickle
  File "<string>", line 126, in <module>
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "<string>", line 2, in read_gpickle
  File "<string>", line 126, in <module>
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
IOError  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: : IOError  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
[[IOErrorErrno 2] No such file or directory: '../DATA/3Dprint/tempo/_InventorsCrossTech': Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_CrossTech':
[
Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_CountryCrossTech'[
Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Applicants_CrossTech'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOErrorIOError: : [[Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_ApplicantInventor'Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Inventors'

Traceback (most recent call last):
  File "<string>", line 122, in <module>
Traceback (most recent call last):
  File "<string>", line 2, in read_gpickle
  File "<string>", line 122, in <module>
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
  File "<string>", line 2, in read_gpickle
IOError  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
: IOError[: Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Applicants'[
Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_References'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOErrorTraceback (most recent call last):
:   File "<string>", line 126, in <module>
[  File "<string>", line 2, in read_gpickle
Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_ApplicantInventor'  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file

IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Inventors'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_References'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Applicants'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Citations'
Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-Networks\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Equivalents'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Citations'
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 2, in read_gpickle
  File "C:\_lab\P2N\Patent2Net\build\P2N-NetworksJS\out00-PYZ.pyz\networkx.utils.decorators", line 198, in _open_file
IOError: [Errno 2] No such file or directory: '../DATA/3Dprint/tempo/_Equivalents'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "<string>", line 64, in <module>
IOError  File "C:\_lab\P2N\Patent2Net\build\FormateExportPivotTable\out00-PYZ.pyz\P2N_Lib", line 2127, in LoadBiblioFile
: IOError[Errno 2] No such file or directory: '..//DATA//3Dprint//PatentBiblios//Families3Dprint': [
Errno 2] No such file or directory: '..//DATA//3Dprint//PatentBiblios//Families3Dprint'
Traceback (most recent call last):
  File "<string>", line 210, in <module>
NameError: name 'LstBrevet' is not defined
Traceback (most recent call last):
  File "<string>", line 204, in <module>
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: '..//DATA//3Dprint//PatentContents//Claims/*.*'
Traceback (most recent call last):
  File "<string>", line 62, in <module>
NameError: name 'data' is not defined
3Dprint.cql  processed
...
Done!
Appuyez sur une touche pour continuer...

**Comment by Quoniam** [comment]
Hi..
With P2N version P2N_Version(2)25-Jan-2017
still an error with the 3DPrint case

Traceback (most recent call last):
  File "OPSGatherContentsV2-Iramuteq.py", line 229, in <module>
  File "P2N_Lib.py", line 2307, in MakeIram2
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
Failed to execute script OPSGatherContentsV2-Iramuteq

[3Dprint error.txt](https://github.com/Patent2net/P2N/files/747409/3Dprint.error.txt)
[3Dprint.cql.txt](https://github.com/Patent2net/P2N/files/747410/3Dprint.cql.txt)
[3DPrint_ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/747411/3DPrint_ErrorsLogs.zip)

sorry 3Dprint P2N result is too big
