### ISSUE TITLE
Unable to run the built-in "Lentille" Example

### ISSUE THREAD

**Issue by smorvan** [Patent2net/P2N#23]
The supplied example ("Lentille") does not seem to work.

The directories are only partially filled, there is no Lentille.html file generated. Installation was made via 'python setup.py install').

Reported version (using 'p2n --version' is 2.1.0, but I suspect it is 3.0.0.dev5 (obtained via 'git clone -b develop https://github.com/Patent2net/P2N.git').

**Comment by amotl** [comment]
Dear @smorvan,

thanks for writing in, we will try to reproduce your problem and get back to you. Can we humbly ask you in turn to run these steps and check if that works on your machine?

## Setup 

    # Create and activate Python 2 virtualenv
    virtualenv --python=python2 .venv27
    source .venv27/bin/activate

    # Install "pygraphviz" on Mac OS X, skip when running a different OS
    pip install --install-option="--include-path=/opt/local/include" --install-option="--library-path=/opt/local/lib" "pygraphviz==1.3.1"

    # Install "patent2net" module
    python setup.py install


## Usage

    # Set OPS API credentials
    p2n ops init --key={YOUR_OPS_KEY} --secret={YOUR_OPS_SECRET}

    # Send example request
    p2n adhoc list --expression='TA=lentille'

## Remarks
- `p2n --version` is just wrong here, we will fix it.
- We would recommend using the "`python setup.py develop`" target here in order to be able to edit the code in the working tree.

Thanks in advance for your efforts.

With kind regards,
Andreas.

**Comment by amotl** [comment]
When running all data acquisition and transformation steps

    export P2N_CONFIG=`pwd`/RequestsSets/Lentille.cql
    p2n run

`patent2net` indeed croaks when running `p2n images`

```
Processing patent CA931760
Traceback (most recent call last):
  File "OPSGatherContentsV2-Images.py", line 127, in <module>
    biblio_file = LoadBiblioFile(ResultBiblioPath, ndf)
  File "/Users/amo/tmp/ip-tools/P2N/Patent2Net/P2N_Lib.py", line 2256, in LoadBiblioFile
    with open(rep + '//Description' + name, 'r') as fic:
IOError: [Errno 2] No such file or directory: '..//DATA/Lentille//PatentBiblios//DescriptionFamiliesLentille'
2018-03-20 04:50:40,561 [p2n.util                 ] ERROR  : Command "python OPSGatherContentsV2-Images.py /Users/amo/tmp/ip-tools/P2N/RequestsSets/Lentille.cql" failed with return code 1
```

We will check what could be wrong there.

**Comment by amotl** [comment]
We just added some commits as an attempt to improve the situation. Can we humbly ask you to try again after a `git pull`:

    export P2N_CONFIG=`pwd`/RequestsSets/Lentille.cql
    p2n run
    open DATA/Lentille.html

We also fixed `p2n --version`:

    $ p2n --version
    Patent2Net 3.0.0-dev6

Thanks again,
Andreas.
