### ISSUE TITLE
Cannot load cles-epo.txt

### ISSUE THREAD

**Issue by richard-thonig** [Patent2net/P2N#28]
Hi, sorry to bother if this turns out to be really stupid... I just started to use your software. I'm confident I followed the installation steps in the wiki.
I run into the following error, eventhough, I have created the file cles-epo.txt with the EPO-Token in C:\P2N-V2\
Could it be that there needs to be a  '..\cles-epo.txt' instead of  '../cles-epo.txt' ?
I'm running the 32-bit version of p2n on Windows 10.
Please see the following output of CollectETraite:

"If error appears, contribute in github! https://github.com/Patent2net/P2N
Or register an issue... when we have time.
        1 file(s) copied.
        1 file(s) copied.
done saving requete, replaced by ..\REQUESTS\F24S.cql
Traceback (most recent call last):
  File "OPSGatherPatentsv2.py", line 53, in <module>
  File "config.py", line 17, in read
IOError: [Errno 2] No such file or directory: '../cles-epo.txt'  "

**Comment by Patent2net** [comment]
Hi,
sorry to answer so late... 
Indeed, this version should work on windows. Are you sure of your filename (sometimes Windows places the first letter in uppercase? 
I can't reproduce this error.
Best,
