### ISSUE TITLE
Family Gathering error

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#6]
There are 2 cases that produce the above error.
As attached, the cql files, the error log in zip, the print screen
Like that it is possible to reproduce the case... and please solve it!!
Regards
[rare_earth.cql.TXT](https://github.com/Patent2net/P2N/files/658906/rare_earth.cql.TXT)
[tuberculosis.cql.TXT](https://github.com/Patent2net/P2N/files/658907/tuberculosis.cql.TXT)
[Rare Earth ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/658908/Rare.Earth.ErrorsLogs.zip)
[Tuberculosis ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/658909/Tuberculosis.ErrorsLogs.zip)
[Tuberculosis Error.TXT](https://github.com/Patent2net/P2N/files/658910/Tuberculosis.Error.TXT)
[Rare Earth Errors.txt](https://github.com/Patent2net/P2N/files/658911/Rare.Earth.Errors.txt)

Traceback (most recent call last):
  File "<string>", line 191, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 2357, in GetFamilly
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 1861, in PreExtractPatentsData
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 1905, in ExtractPatentsData
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 2234, in MakeIram
KeyError: 'year'

**Comment by cvanderlei** [comment]
Problem found... testing the solution.

**Comment by Quoniam** [comment]
Ooooohhh Super!!! the above cql... produce similar error... for test..

[dengue.cql.txt](https://github.com/Patent2net/P2N/files/660706/dengue.cql.txt)

**Comment by cvanderlei** [comment]
Some times the system stops while processing the OPSGatherAugment-Families scritpt. 
In those cases, it is necessary to restart all the job.
Anybody knows why this happen?

**Comment by cvanderlei** [comment]
The correction is working, but... a similar problem occurs in another point (the third one found). 
Fixed, testing again.

**Comment by Quoniam** [comment]
The Rare earth case and tuberculosis are solved!!!
but the dengue case still not solved...


Traceback (most recent call last):
  File "<string>", line 191, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 2370, in GetFamilly
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 1865, in PreExtractPatentsData
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 1876, in ExtractPatentsData
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherAugment-Families\out00-PYZ.pyz\P2N_Lib", line 2732, in ProcessBiblio
KeyError: u'document-id'
C:\Users\Public\Softs\LUCP2N~2\PATENT~1\dateutil\parser.py:330: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 195, in <module>
NameError: name 'fictemp1' is not defined

**Comment by Quoniam** [comment]
All cases corrected!!
